image: archlinux
secrets:
- 3dcea276-38d6-4a7e-85e5-20cbc903e1ea
packages:
  - go
sources:
  - https://git.sr.ht/~mariusor/othrys
tasks:
  - setup: |
      cd othrys && make download
  - build: |
      cd othrys && make clean all
  - tests: |
      cd othrys
      make test
      make coverage
  - push_to_github: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      cd othrys
      git remote add hub git@github.com:mariusor/othrys
      git push hub --force --all
